<a href="https://colab.research.google.com/github/andrewseltzer99/Basic-Numpy-Utilization/blob/main/Basic_Numpy_Utilization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
import pandas as pd
# Type your solution here
#1-1
frame = pd.DataFrame(data)
#1-2
newframe = frame[(frame["job"] == "teacher") | (frame["job"] == "psychologist")]
finalframe = newframe[(newframe["num_cars"]>newframe["family_size"])]

print("\n1-2\n", finalframe, sep="")

#1-3
num3frame = frame[(frame["family_size"] < 3) & (frame["num_cars"]>0)]
print("\n1-3\n",num3frame, sep="")

#1-4
print("\n1-4\n", len(frame.job.unique()), sep="")


1-2
   name           job  family_size  num_cars
5  Lisa  psychologist            3         4

1-3
   name           job  family_size  num_cars
4  Ryan  psychologist            2         2

1-4
4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
import pandas as pd
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))

weights = pd.Series(np.linspace(1, 10, 10))


In [ ]:
means = weights.groupby(fruit).mean()
print(means)

apple     4.000000
banana    6.500000
carrot    5.666667
dtype: float64


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here
#3-1
ind = np.argsort(course_name)
print(ind)

#3-2
print()
words = np.char.startswith(course_name, "P")
print(words)

[1 3 0 2 4]

[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Type your solution here
#4-1
reverse = student_id[::-1]
print(student_id)
print(reverse)

#4-2
array_copy = np.sort(student_id)[::-1]
print(array_copy[0], array_copy[1], array_copy[2])

[6230 5241 5202 4532 1682 1671 1023]
[1023 1671 1682 4532 5202 5241 6230]
6230 5241 5202


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here
# Hint: you can use arange to start off
arr = np.arange(1, 100)
# find  multiple of 3 or 5
nums = arr[(arr % 3 == 0) | (arr % 5 == 0)]
print(nums.sum())

2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 6-1
print("array before\n", arr, sep="")
arr[:, [2, 1]] = arr[:, [1, 2]]
print("\narray after\n",arr, sep="")
# 6-2

arr[[0, 1]] = arr[[1, 0]]
print("\nnow swapping row 1 and 0\n", arr, sep="")

array before
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

array after
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]

now swapping row 1 and 0
[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
